# Generated by Django 4.0.5 on 2023-02-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_contas_saldo_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerais',
            name='data_do_Fechamento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
