# Generated by Django 4.0.5 on 2023-02-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0010_alter_gerais_data_do_fechamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerais',
            name='data_do_Fechamento',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
