# Generated by Django 4.0.5 on 2023-02-17 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0015_remove_gerais_data_do_fechamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerais',
            name='data_do_Fechamento1',
            field=models.DateField(blank=True, null=True),
        ),
    ]
