# Generated by Django 4.0.5 on 2023-02-17 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0016_gerais_data_do_fechamento1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gerais',
            old_name='data_do_Fechamento1',
            new_name='data_do_Fechamento',
        ),
    ]
