# Generated by Django 4.0.5 on 2023-02-17 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0018_alter_gerais_data_do_fechamento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gerais',
            old_name='data_do_Fechamento',
            new_name='data_do_Fechamento1',
        ),
    ]
